services:
  # Define the database service
  database:
    image: tugboatqa/mariadb:10.5
    commands:
      # Configure the database for better performance
      init:
        - mysql -e "SET GLOBAL max_allowed_packet=536870912;"
        - echo "max_allowed_packet=536870912" >> /etc/mysql/conf.d/tugboat.cnf

  # Define the PHP/Apache service
  php:
    image: tugboatqa/php:8.1-apache
    default: true
    depends: database
    commands:
      init:
        # Install required PHP extensions and Apache modules
        - docker-php-ext-install opcache
        - a2enmod headers rewrite

        # Link the document root to the expected path
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"

        # Create necessary directories
        - mkdir -p "${TUGBOAT_ROOT}/files-private"
        - mkdir -p "${DOCROOT}/sites/default/files/translations"

        # Set proper file permissions
        - chgrp -R www-data "${DOCROOT}/sites/default/files"
        - find "${DOCROOT}/sites/default/files" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \;

        # Create symlink for drush
        - ln -snf "${TUGBOAT_ROOT}/vendor/bin/drush" /usr/local/bin/drush

      update:
        # Copy Tugboat-specific settings
        - cp "${TUGBOAT_ROOT}/.tugboat/settings.local.php" "${DOCROOT}/sites/default/settings.local.php"

        # Install/update packages managed by composer
        - composer install --optimize-autoloader
        - composer require --dev drupal/stage_file_proxy

      build:
        # Import configuration and update database
        - vendor/bin/drush cache:rebuild
        - vendor/bin/drush config:import -y
        - vendor/bin/drush updatedb -y
        - vendor/bin/drush cache:rebuild

        # Enable and configure stage_file_proxy
        - vendor/bin/drush pm:enable --yes stage_file_proxy
        - vendor/bin/drush config:set --yes stage_file_proxy.settings origin "https://www.example.com"
        - vendor/bin/drush config:set --yes stage_file_proxy.settings origin_dir "sites/default/files"

        # Final cache rebuild
        - vendor/bin/drush cache:rebuild 